
services:
  init:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:v0.2.1
    volumes:
      - ./arch/.arch-data:/arch_data
      - ./arch/.arch-data/bootnode:/bootnode_data
      - ./arch/scripts/init.sh:/usr/local/bin/init.sh
    command: /usr/local/bin/init.sh
    environment:
      - REPLICA_COUNT=2

  bootnode:
    platform: linux/amd64
    image: ghcr.io/arch-network/bootnode:v0.2.1
    command: /usr/local/bin/bootnode.sh
    ports:
      - 19001:19001
    environment:
      RUST_LOG: "info"
      RUST_BACKTRACE: "1"
      BOOTNODE_P2P_PORT: 19001
      NETWORK_MODE: "localnet"
      DATA_DIR: /arch_data
    volumes:
      - ./arch/.arch-data/bootnode:/arch_data
      - ./arch/scripts/bootnode.sh:/usr/local/bin/bootnode.sh
    depends_on:
      - init
    networks:
      arch-network:
        ipv4_address: 172.30.0.250

  leader:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:v0.2.1
    ports:
      - 19002:19002
      - 9002:9002
    command: /usr/local/bin/leader.sh
    environment:
      RUST_LOG: "info,validator=info"
      RUST_BACKTRACE: "1"
      NETWORK_MODE: localnet
      DATA_DIR: /arch-data
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOTNODE_P2P_PORT: 19001
      RPC_BIND_IP: 0.0.0.0
      RPC_BIND_PORT: 9002
      P2P_BIND_PORT: 19002
#      BITCOIN_RPC_ENDPOINT: bitcoin-node.dev.aws.archnetwork.xyz
#      BITCOIN_RPC_PORT: 18443
#      BITCOIN_RPC_USERNAME: bitcoin
#      BITCOIN_RPC_PASSWORD: 428bae8f3c94f8c39c50757fc89c39bc7e6ebc70ebf8f618
#      BITCOIN_RPC_WALLET: "devwallet"
      BITCOIN_RPC_ENDPOINT: bitcoin
      BITCOIN_RPC_PORT: 18443
      BITCOIN_RPC_USERNAME: user
      BITCOIN_RPC_PASSWORD: password
      BITCOIN_RPC_WALLET: "testwallet"
    volumes:
      - ./arch/.arch-data:/arch_data
      - ./arch/.arch-data/bootnode:/bootnode_data:ro
      - ./arch/scripts/leader.sh:/usr/local/bin/leader.sh
    depends_on:
      - bootnode
    networks:
      - arch-network

  validator-1:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:v0.2.1
    command: /usr/local/bin/validator.sh
    environment:
      VALIDATOR_NUMBER: "1"
      RUST_LOG: "info,validator=info"
      RUST_BACKTRACE: "1"
      NETWORK_MODE: "localnet"
      DATA_DIR: /arch-data
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOTNODE_P2P_PORT: 19001
      RPC_BIND_IP: 0.0.0.0
      RPC_BIND_PORT: 9003
      P2P_BIND_PORT: 19003
#      BITCOIN_RPC_ENDPOINT: bitcoin-node.dev.aws.archnetwork.xyz
#      BITCOIN_RPC_PORT: 18443
#      BITCOIN_RPC_USERNAME: bitcoin
#      BITCOIN_RPC_PASSWORD: 428bae8f3c94f8c39c50757fc89c39bc7e6ebc70ebf8f618
#      BITCOIN_RPC_WALLET: "devwallet"
      BITCOIN_RPC_ENDPOINT: bitcoin
      BITCOIN_RPC_PORT: 18443
      BITCOIN_RPC_USERNAME: user
      BITCOIN_RPC_PASSWORD: password
      BITCOIN_RPC_WALLET: "testwallet"
    volumes:
      - ./arch/.arch-data/validators:/arch_data
      - ./arch/.arch-data/bootnode:/bootnode_data:ro
      - ./arch/scripts/validator.sh:/usr/local/bin/validator.sh
    depends_on:
      - bootnode
      - leader
    ports:
      - 19003:19003
      - 9003:9003
    networks:
      - arch-network

  validator-2:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:v0.2.1
    command: /usr/local/bin/validator.sh
    environment:
      VALIDATOR_NUMBER: "2"
      RUST_LOG: "info,validator=info"
      RUST_BACKTRACE: "1"
      NETWORK_MODE: "localnet"
      DATA_DIR: /arch-data
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOTNODE_P2P_PORT: 19001
      RPC_BIND_IP: 0.0.0.0
      RPC_BIND_PORT: 9004
      P2P_BIND_PORT: 19004
#      BITCOIN_RPC_ENDPOINT: bitcoin-node.dev.aws.archnetwork.xyz
#      BITCOIN_RPC_PORT: 18443
#      BITCOIN_RPC_USERNAME: bitcoin
#      BITCOIN_RPC_PASSWORD: 428bae8f3c94f8c39c50757fc89c39bc7e6ebc70ebf8f618
#      BITCOIN_RPC_WALLET: "devwallet"
      BITCOIN_RPC_ENDPOINT: bitcoin
      BITCOIN_RPC_PORT: 18443
      BITCOIN_RPC_USERNAME: user
      BITCOIN_RPC_PASSWORD: password
      BITCOIN_RPC_WALLET: "testwallet"
    volumes:
      - ./arch/.arch-data/validators:/arch_data
      - ./arch/.arch-data/bootnode:/bootnode_data:ro
      - ./arch/scripts/validator.sh:/usr/local/bin/validator.sh
    depends_on:
      - bootnode
      - leader
      - validator-1
    ports:
      - 19004:19004
      - 9004:9004
    networks:
      - arch-network

  bitcoin:
    image: bitcoin
    platform: linux/amd64
    container_name: bitcoin
    restart: always
    ports:
      - "18443:18443"
      - "28332:28332"
    stop_grace_period: 5s
    networks:
      - arch-network

  fulcrum:
    image: fulcrum
    container_name: fulcrum
    platform: linux/amd64
    depends_on:
      - bitcoin
    expose:
      - "50001"
      - "50002"
    ports:
      - 50001:50001
      - 50002:50002
    restart: always
    stop_grace_period: 10s
    networks:
      - arch-network

  mempool-frontend:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
    image: mempool/frontend:latest
    depends_on:
      - mempool-backend
    container_name: mempool-frontend
    user: "1000:1000"
    restart: always
    stop_grace_period: 5s
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 1080:8080
    networks:
      - arch-network

  mempool-backend:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "fulcrum"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "bitcoin"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "password"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    depends_on:
      - mempool-db
    container_name: mempool-backend
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 5s
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - .datapi/:/backend/cache
    networks:
      - arch-network

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    depends_on:
      - fulcrum
    container_name: mempool-db
    restart: always
    stop_grace_period: 5s
    networks:
      - arch-network

networks:
  arch-network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
