
services:

  arch-local-validator:
    platform: linux/amd64
    container_name: arch-local-validator
    image: ghcr.io/arch-network/local_validator:v0.2.17
    ports:
      - 9002:9002
    command: /usr/bin/local_validator --rpc-bind-ip 0.0.0.0 --rpc-bind-port 9002 --bitcoin-rpc-endpoint bitcoin --bitcoin-rpc-port 18443 --bitcoin-rpc-username user --bitcoin-rpc-password password
    environment:
      RUST_LOG: "info"
      RUST_BACKTRACE: "1"

  bitcoin:
    image: ${BITCOIN_IMAGE:-bitcoin}
    platform: linux/amd64
    container_name: bitcoin
    restart: always
    ports:
      - "18443:18443"
      - "28332:28332"
    stop_grace_period: 2s

  ordinals-ord:
    platform: linux/amd64
    container_name: ord
    restart: unless-stopped
    image: ${ORD_IMAGE:-ord}
    ports:
      - "7080:7080"
    depends_on:
      - bitcoin
    environment:
      CORE_RPC_HOST: "bitcoin"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "password"
      PORT: "7080"
    healthcheck:
      test: curl -f localhost:7080/blockheight || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  electrs:
    image: mempool/electrs:v3.0.0
    container_name: electrs
    platform: linux/amd64
    depends_on:
      - bitcoin
    expose:
      - "3001"
      - "50001"
    ports:
      - 50001:50001
      - 3001:3001
    entrypoint: /bin/electrs
    command: |
      --jsonrpc-import
      --network=regtest
      --daemon-rpc-addr=bitcoin:18443
      --lightmode
      --index-unspendables
      --utxos-limit=100000
      --electrum-txs-limit=100000
      --address-search
      --cookie=user:password
      --cors='*'
      --http-addr=0.0.0.0:3001
      --electrum-rpc-addr=0.0.0.0:50001
      -vvvv
    volumes:
      - electrs_data:/data/db
    restart: always
    stop_grace_period: 2s

  mempool-frontend:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
    image: mempool/frontend:v3.0.1
    depends_on:
      - mempool-backend
    container_name: mempool-frontend
    user: "1000:1000"
    restart: always
    stop_grace_period: 2s
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 1080:8080

  mempool-backend:
    environment:
      MEMPOOL_BACKEND: "esplora"
      ESPLORA_REST_API_URL: "http://electrs:3001"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "bitcoin"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "password"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:v3.0.1
    depends_on:
      - mempool-db
    container_name: mempool-backend
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 2s
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - .datapi/:/backend/cache

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    depends_on:
      - electrs
    container_name: mempool-db
    restart: always
    stop_grace_period: 2s


volumes:
  electrs_data:
