
version: '3.7'

x-environment: &common-arch-environment
  RUST_LOG: "info, validator=debug" # debug, info, error, warn, trace, off
  RUST_BACKTRACE: "1" # enable error stack traces
  NETWORK_MODE: "localnet" # devnet, testnet, mainnet
  PRIVATE_KEY_PASSWORD: "" # Provide a password if you'd like to encrypt the local node keys.
  RPC_BIND_IP: "0.0.0.0" # bind to all IPs
  LEADER_PEERID: "16Uiu2HAkwZ1Qt1W71Jv5SrQpskVDze6zMckRkYwDaw3QveL8yQ7K"
#  BITCOIN_RPC_ENDPOINT: "bitcoin" # Replace with your bitcoin node's RPC endpoint
#  BITCOIN_RPC_PORT: "18443" # Replace with your bitcoin node's RPC port
#  BITCOIN_RPC_USERNAME: "user" # Replace with your bitcoin node's RPC username (if any)
#  BITCOIN_RPC_PASSWORD: "password" # Replace with your bitcoin node's RPC password (if any)
#  BITCOIN_RPC_WALLET: "testwallet"   # Replace with the name of the wallet to be used by arch-node
  BITCOIN_RPC_ENDPOINT: "bitcoin-node.dev.aws.archnetwork.xyz" # Replace with your bitcoin node's RPC endpoint
  BITCOIN_RPC_PORT: "18443" # Replace with your bitcoin node's RPC port
  BITCOIN_RPC_USERNAME: "bitcoin" # Replace with your bitcoin node's RPC username (if any)
  BITCOIN_RPC_PASSWORD: "428bae8f3c94f8c39c50757fc89c39bc7e6ebc70ebf8f618" # Replace with your bitcoin node's RPC password (if any)
  BITCOIN_RPC_WALLET: "devwallet"   # Replace with the name of the wallet to be used by arch-node
  BOOT_NODE_ENDPOINT: "/ip4/172.30.0.10/tcp/19001/p2p/16Uiu2HAmA5DZfSpvcEqpuYyPjDSgx5G3e7bJLbgK5m5LBc6rnLes"
  DATA_DIR: "/arch-data"

services:
  bootnode:
    platform: linux/amd64
    image: ghcr.io/arch-network/bootnode@sha256:676c741d6a4be36f314f8dba1396d0701c38efe48f09267c06698664aa9245fa
    ports:
      - 19001:19001
    environment:
      RUST_LOG: "info" # debug, info, error, warn, trace, off
      RUST_BACKTRACE: "1" # enable error stack traces

      NETWORK_MODE: "localnet" # localnet, devnet, testnet, mainnet
      DATA_DIR: "/arch-data" # directory where data will be stored
    volumes:
      - ./arch/data/bootnode:/arch-data
    networks:
      arch-network:
        ipv4_address: 172.30.0.10 # If you change this IP, make sure to update the validator endpoint below.

  leader:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator@sha256:c89d59d94dc73fc65056502b9ad2c6d3d959b65ad46e236c67fcd59086dedf69
    ports:
      - 19002:19002
      - 9002:9002
    environment:
      <<: *common-arch-environment
      RPC_BIND_PORT: "9002" # TCP 9002
      P2P_BIND_PORT: "19002"
    volumes:
      - ./arch/data/leader:/arch-data
    depends_on:
      - bootnode
    networks:
      - arch-network

  validator-1:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator@sha256:c89d59d94dc73fc65056502b9ad2c6d3d959b65ad46e236c67fcd59086dedf69
    ports:
      - 19003:19003
      - 9003:9003
    environment:
      <<: *common-arch-environment
      RPC_BIND_PORT: "9003" # TCP 9002
      P2P_BIND_PORT: "19003"
    volumes:
      - ./arch/data/validator-1:/arch-data
    depends_on:
      - bootnode
    networks:
      - arch-network

  validator-2:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator@sha256:c89d59d94dc73fc65056502b9ad2c6d3d959b65ad46e236c67fcd59086dedf69
    ports:
      - 19004:19004
      - 9004:9004
    environment:
      <<: *common-arch-environment
      RPC_BIND_PORT: "9004" # TCP 9004
      P2P_BIND_PORT: "19004"
    volumes:
      - ./arch/data/validator-2:/arch-data
    depends_on:
      - bootnode
    networks:
      - arch-network

#  bitcoin:
#    image: bitcoin
#    platform: linux/amd64
#    container_name: bitcoin
#    restart: always
#    ports:
#      - "18443:18443"
#      - "28332:28332"
#    stop_grace_period: 5s

#
#  fulcrum:
#    image: fulcrum
#    container_name: fulcrum
#    platform: linux/amd64
#    depends_on:
#      - bitcoin
#    expose:
#      - "50001"
#      - "50002"
#    ports:
#      - 50001:50001
#      - 50002:50002
#    restart: always
#    stop_grace_period: 10s
#
#  mempool-web:
#    environment:
#      FRONTEND_HTTP_PORT: "8080"
#      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
#    image: mempool/frontend:latest
#    depends_on:
#      - mempool-api
#    container_name: mempool-web
#    user: "1000:1000"
#    restart: always
#    stop_grace_period: 5s
#    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
#    ports:
#      - 1080:8080
#
#  mempool-api:
#    environment:
#      MEMPOOL_BACKEND: "electrum"
#      ELECTRUM_HOST: "fulcrum"
#      ELECTRUM_PORT: "50001"
#      ELECTRUM_TLS_ENABLED: "false"
#      CORE_RPC_HOST: "bitcoin"
#      CORE_RPC_PORT: "18443"
#      CORE_RPC_USERNAME: "user"
#      CORE_RPC_PASSWORD: "password"
#      DATABASE_ENABLED: "true"
#      DATABASE_HOST: "mempool-db"
#      DATABASE_DATABASE: "mempool"
#      DATABASE_USERNAME: "mempool"
#      DATABASE_PASSWORD: "mempool"
#      STATISTICS_ENABLED: "true"
#    image: mempool/backend:latest
#    depends_on:
#      - mempool-db
#    container_name: mempool-api
#    user: "1000:1000"
#    restart: on-failure
#    stop_grace_period: 5s
#    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
#    volumes:
#      - .datapi/:/backend/cache
#
#  mempool-db:
#    environment:
#      MYSQL_DATABASE: "mempool"
#      MYSQL_USER: "mempool"
#      MYSQL_PASSWORD: "mempool"
#      MYSQL_ROOT_PASSWORD: "admin"
#    image: mariadb:10.5.8
#    depends_on:
#      - fulcrum
#    container_name: mempool-db
#    restart: always
#    stop_grace_period: 5s

networks:
  arch-network:
    ipam:
      driver: default # bridge
      config:
        - subnet: 172.30.0.0/24 # If you change the subnet, make sure to update the bootnode ip above.
          gateway: 172.30.0.1