
version: '3.7'

x-environment: &common-arch-environment
  LOG_LEVEL: "debug" # debug, info, error, warn, trace, off
  RUST_BACKTRACE: "1" # enable error stack traces
  NETWORK_MODE: "devnet" # devnet, testnet, mainnet
  PRIVATE_KEY_PASSWORD: "" # Provide a password if you'd like to encrypt the local node keys.
  RPC_BIND_IP: "0.0.0.0" # bind to all IPs
  BITCOIN_RPC_ENDPOINT: "bitcoin" # Replace with your bitcoin node's RPC endpoint
  BITCOIN_RPC_PORT: "18443" # Replace with your bitcoin node's RPC port
  BITCOIN_RPC_USERNAME: "user" # Replace with your bitcoin node's RPC username (if any)
  BITCOIN_RPC_PASSWORD: "password" # Replace with your bitcoin node's RPC password (if any)
  BITCOIN_RPC_WALLET: "testwallet"   # Replace with the name of the wallet to be used by arch-node
  RISC0_DEV_MODE: "1"
  DATA_DIR: "/arch-data"


services:
  bootnode:
    image: ghcr.io/arch-network/node:latest
    platform: linux/amd64
    container_name: bootnode
    restart: always
    ports:
      - 9001:9001
    environment:
      <<: *common-arch-environment
      ARCH_NODES: http://bootnode:9001,http://arch-node:9002,http://zkvm:9003
      PROVER_ENDPOINT: http://zkvm:8001
      IS_BOOT_NODE: "true"
      RPC_BIND_PORT: "9001"
    volumes:
      - ./.arch-data/0:/arch-data

  arch-node:
    image: ghcr.io/arch-network/node:latest
    platform: linux/amd64
    container_name: arch-node
    restart: always
    ports:
      - 9002:9002
    environment:
      <<: *common-arch-environment
      BOOT_NODE_ENDPOINT: "http://bootnode:9001"
      PROVER_ENDPOINT: "http://zkvm:8001"
      RPC_BIND_PORT: "9002"
    depends_on:
      - bootnode
    volumes:
      - ./.arch-data/1:/arch-data

  zkvm:
    image: ghcr.io/arch-network/zkvm:latest
    platform: linux/amd64
    container_name: zkvm
    restart: always
    ports:
      - 9003:9003
      - 8001:8001
    environment:
      <<: *common-arch-environment
      BOOT_NODE_ENDPOINT: "http://bootnode:9001"
      PROVER_ENDPOINT: "http://zkvm:8001"
      RPC_BIND_PORT: "9003"
      ZKVM_RPC_BIND_IP: "0.0.0.0" # bind to all IPs
      ZKVM_RPC_BIND_PORT: "8001" # TCP 8001
      ARCH_BOOT_NODE_URL: "http://bootnode:9001"
    depends_on:
      - bootnode
    volumes:
      - ./.arch-data/2:/arch-data

  init-bootnode:
    build: ./docker/init
    depends_on:
      bootnode:
        condition: service_started

  bitcoin:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/bitcoin:latest
    platform: linux/amd64
    container_name: bitcoin
    restart: always
    ports:
      - 18443:18443
      - 18444:18444
      - 18445:18445

  fulcrum:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/fulcrum:latest
    container_name: fulcrum
    platform: linux/amd64
    depends_on:
      - bitcoin
    expose:
      - "50001"
      - "50002"
    ports:
      - 50001:50001
      - 50002:50002
    restart: always
    stop_grace_period: 10s

  mempool-web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
    image: mempool/frontend:latest
    depends_on:
      - mempool-api
    container_name: mempool-web
    user: "1000:1000"
    restart: always
    stop_grace_period: 5s
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 1080:8080

  mempool-api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "fulcrum"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "bitcoin"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "password"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    depends_on:
      - mempool-db
    container_name: mempool-api
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 5s
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - .datapi/:/backend/cache

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    depends_on:
      - fulcrum
    container_name: mempool-db
    restart: always
    stop_grace_period: 5s