.PHONY: test

build:
	cd exchange && make build && cd ../coin-proxy && make build && cd ..

lint:
	cd exchange && make lint && cd ../coin-proxy && make lint && cd ..

format:
	cd exchange && make format && cd ../coin-proxy && make format && cd ..

test:
	cd exchange && make test && cd ../coin-proxy && make test && cd ..
